# Workflow para construir e implantar um aplicativo Angular no GitHub Pages
name: Build and Deploy to GitHub Pages

on:
  # Roda quando um push é feito para a branch `main`
  push:
    branches: [ "main" ]
  # Permite que você execute este workflow manualmente na aba Actions
  workflow_dispatch:

# Define permissões para o GITHUB_TOKEN para permitir a implantação no GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Permite apenas uma implantação simultânea, cancelando execuções mais antigas
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Job de implantação
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Angular App
        # IMPORTANTE: O --base-href deve corresponder ao nome do seu repositório
        run: npm run build -- --base-href /hemocentro-cpf-input-test/

      - name: Set up Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Faz o upload do diretório de build gerado pelo Angular
          path: './dist/hemocentro-cpf-input-test/browser'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
